kind: Deployment
apiVersion: apps/v1
metadata:
  name: < app 이름 >
  labels:
    app: < app 이름 >
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: < app 이름 >
  template:
    metadata:
      labels:
        app: < app 이름 >
        version: v1
    spec:
      containers:
      - name: < app 이름 >
        image: < docker ID>/< app 이름 >:v1.0.0
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: < app 이름 >
spec:
  selector:
    app: < app 이름 >
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
